// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	xcloudnativeiov1alpha1 "github.com/xcloudnative/xcloud/pkg/apis/xcloudnative.io/v1alpha1"
	versioned "github.com/xcloudnative/xcloud/pkg/client/clientset/versioned"
	internalinterfaces "github.com/xcloudnative/xcloud/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/xcloudnative/xcloud/pkg/client/listers/xcloudnative.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// XflowInformer provides access to a shared informer and lister for
// Xflows.
type XflowInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.XflowLister
}

type xflowInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewXflowInformer constructs a new informer for Xflow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewXflowInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredXflowInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredXflowInformer constructs a new informer for Xflow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredXflowInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XcloudnativeV1alpha1().Xflows(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XcloudnativeV1alpha1().Xflows(namespace).Watch(options)
			},
		},
		&xcloudnativeiov1alpha1.Xflow{},
		resyncPeriod,
		indexers,
	)
}

func (f *xflowInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredXflowInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *xflowInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&xcloudnativeiov1alpha1.Xflow{}, f.defaultInformer)
}

func (f *xflowInformer) Lister() v1alpha1.XflowLister {
	return v1alpha1.NewXflowLister(f.Informer().GetIndexer())
}
