// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/xcloudnative/xcloud/pkg/client/clientset/versioned/typed/xcloudnative.io/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeXcloudnativeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeXcloudnativeV1alpha1) Xflows(namespace string) v1alpha1.XflowInterface {
	return &FakeXflows{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeXcloudnativeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
