// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// XflowListerExpansion allows custom methods to be added to
// XflowLister.
type XflowListerExpansion interface{}

// XflowNamespaceListerExpansion allows custom methods to be added to
// XflowNamespaceLister.
type XflowNamespaceListerExpansion interface{}
