// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/xcloudnative/xcloud/pkg/apis/xcloudnative.io/v1alpha1"
	scheme "github.com/xcloudnative/xcloud/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// XflowsGetter has a method to return a XflowInterface.
// A group's client should implement this interface.
type XflowsGetter interface {
	Xflows(namespace string) XflowInterface
}

// XflowInterface has methods to work with Xflow resources.
type XflowInterface interface {
	Create(*v1alpha1.Xflow) (*v1alpha1.Xflow, error)
	Update(*v1alpha1.Xflow) (*v1alpha1.Xflow, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Xflow, error)
	List(opts v1.ListOptions) (*v1alpha1.XflowList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Xflow, err error)
	XflowExpansion
}

// xflows implements XflowInterface
type xflows struct {
	client rest.Interface
	ns     string
}

// newXflows returns a Xflows
func newXflows(c *XcloudnativeV1alpha1Client, namespace string) *xflows {
	return &xflows{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the xflow, and returns the corresponding xflow object, and an error if there is any.
func (c *xflows) Get(name string, options v1.GetOptions) (result *v1alpha1.Xflow, err error) {
	result = &v1alpha1.Xflow{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("xflows").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Xflows that match those selectors.
func (c *xflows) List(opts v1.ListOptions) (result *v1alpha1.XflowList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.XflowList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("xflows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested xflows.
func (c *xflows) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("xflows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a xflow and creates it.  Returns the server's representation of the xflow, and an error, if there is any.
func (c *xflows) Create(xflow *v1alpha1.Xflow) (result *v1alpha1.Xflow, err error) {
	result = &v1alpha1.Xflow{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("xflows").
		Body(xflow).
		Do().
		Into(result)
	return
}

// Update takes the representation of a xflow and updates it. Returns the server's representation of the xflow, and an error, if there is any.
func (c *xflows) Update(xflow *v1alpha1.Xflow) (result *v1alpha1.Xflow, err error) {
	result = &v1alpha1.Xflow{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("xflows").
		Name(xflow.Name).
		Body(xflow).
		Do().
		Into(result)
	return
}

// Delete takes name of the xflow and deletes it. Returns an error if one occurs.
func (c *xflows) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("xflows").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *xflows) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("xflows").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched xflow.
func (c *xflows) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Xflow, err error) {
	result = &v1alpha1.Xflow{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("xflows").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
